name: C++ Style Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clang-tidy:
      name: clang-tidy
      runs-on: ubuntu-latest
      steps:
        - name: clang-tidy check
          uses: /Tlazypanda/cpp-clang-check@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
